### ISSUE TITLE
Bug in Merge Sort 

### ISSUE THREAD

**Issue by BoolPurist** [jfhr/algodat#16]
# Bug in Merge Sort 

## Problem: 
Functions returns array with changed values instead of just being sorted.

## File with Bug
MergeSort.cs in /AlgoDat/AlgoDatRespo/Algodat/SortAlgorithms/MergeSort.cs

## How to reproduce it:
```C#
var sort = new MergeSort();
var numbers = new int[] { 2, -4, 5 };
sort.SortAscending(numbers);

Console.Write("[ ");
foreach (int number in numbers ) 
{
  Console.Write($"{number} ");
}

Console.WriteLine("]");
```

## Expected Output:
[ -4, 2, 5 ]

## Actual Output:
[ 5. 5, 5 ]

## Suggestion

The Unit test did not detect this bug because it only checks if the array is sorted but not the actual content.
It might be good Idea to define for each test case an desired sorted array to be compared with.

**Comment by jfhr** [comment]
@BoolPurist good find! Fixed this in #17 . Feel free to review the fix if you like
